[package]
name = "hackdose_server_shared"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = { version="1.0.147", features=["serde_derive"] }
chrono = { version="0.4.22", features=["serde"]}