# Configuration for local testing
actors:
  - actor: !Tasmota
      url: http://192.168.178.94
    disable_threshold: 100
    enable_threshold: -100
    duration_seconds: 360
    actor_mode: !Discharge
  - actor: !HS100
      address: 192.168.178.12:9999
    disable_threshold: 100
    enable_threshold: -100
    duration_seconds: 360
    actor_mode:
      !Charge # Start loop via socat -d -d pty,raw,echo=0 pty,raw,echo=0


ttys_location: /dev/pts/5
gpio_power_pin: 38 # Pin 35 in Mango PI
log_location: energy.log
