name: Rust

on:
  pull_request:
    branches: [main]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      RUST_BACKTRACE: full
      RUSTC_WRAPPER: sccache
      SCCACHE_GHA_ENABLED: "true"

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Run sccache-cache
        uses: mozilla-actions/sccache-action@v0.0.3

      - name: Install build dependencies
        run: |
          rustup target add wasm32-unknown-unknown
          cargo install trunk --version "=0.18.3" --locked
          pushd app
          npm ci
          popd

      - name: Check Backend
        run: |
          pushd app
          trunk build --release
          popd
          cargo build
          cargo test
