name: Artifacts

on:
  push:
    branches: [main]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install gcc-riscv64-linux-gnu
          sudo apt-get install gcc-arm-linux-gnueabihf
          rustup target add riscv64gc-unknown-linux-gnu
          rustup target add armv7-unknown-linux-musleabihf
          rustup target add wasm32-unknown-unknown
          cargo install trunk --version "=0.18.3" --locked
          pushd app
          npm ci
          popd

      - name: Build Cache for raspberry pi
        uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Build Front End
        run: |
          pushd app
          trunk build --release
          popd

      - name: Build Artifact for mango pi
        run: |
          cargo build --target=riscv64gc-unknown-linux-gnu --release

      - name: Build Artifact for raspberry pi
        run: |
          cargo build --target=armv7-unknown-linux-musleabihf --release

      - uses: actions/upload-artifact@v3
        with:
          name: mango-pi-executable
          path: target/riscv64gc-unknown-linux-gnu/release/hackdose-server

      - uses: actions/upload-artifact@v3
        with:
          name: raspberry-pi-executable
          path: target/armv7-unknown-linux-musleabihf/release/hackdose-server

      - uses: actions/upload-artifact@v3
        with:
          name: mqtt-client-mango-pi-executable
          path: target/riscv64gc-unknown-linux-gnu/release/hackdose_mqtt_client

      - uses: actions/upload-artifact@v3
        with:
          name: mqtt-client-raspberry-pi-executable
          path: target/armv7-unknown-linux-musleabihf/release/hackdose_mqtt_client
